### PR TITLE
add new application

### PR DESCRIPTION
**Pull request by avcuenes**
new examples using mealpy

### CODE REVIEW

**Comment by avcuenes** [comment]
Okey I gonna add comments

**Comment by avcuenes** [comment]
hi @thieu1995 

I delete unnecessary function and rename of folder with correct one. Can you check ?Thank you:)

**Comment by thieu1995** [comment]
hi @avcuenes ,

Can you delete the .vscode folder? It is trash files.
Also, add reference paper to path planning example, so users will know where to look at when reading your examples.
Thank you

**Comment by avcuenes** [comment]
Hi @thieu1995 

I delete .vscode folder and add reference to algorithm.

**Pull request merged**
